version: "3.8"
services:

  # Applications
  config-service:
    image: config-service
    container_name: config-service
    platform: linux/amd64
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 9888
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888
      - SPRING_PROFILES_ACTIVE=testdata
      
  catalog-service:
    restart: on-failure
    depends_on:
      - config-service
      - polar-postgres
    image: catalog-service
    container_name: catalog-service
    platform: linux/amd64
    ports:
      - 9002:9002    
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      - WAIT_HOSTS=config-service:8888
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=prod
    
  # Backing Services
      
  polar-postgres:
    image: postgres:14.4
    container_name: polar-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=polardb_catalog